#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import sys
from importlib import import_module
from distutils import version


def main():
    if len(sys.argv) < 2:
        sys.exit(1)
    dist = sys.argv[1]
    required = sys.argv[2] if len(sys.argv) > 2 else None

    try:
        _module = import_module(dist)
        _version = _module.__version__
    except ImportError as e:
        sys.exit(1)
    else:
        _version = version.LooseVersion(_version)
        if required is None:
            print(_version)
            sys.exit(0)
        required = version.LooseVersion(required)
        if _version >= required:
            print(_version)
            sys.exit(0)
        else:
            print(_version, file=sys.stderr)
            sys.exit(1)


if __name__ == '__main__':
    main()
